services:
  landing:
    build: .
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared_proxy_net
      - traefik.http.routers.landing.rule=Host(`gehrer-ai.com`) || Host(`www.gehrer-ai.com`)
      - traefik.http.routers.landing.tls=true
      - traefik.http.routers.landing.entrypoints=web,websecure
      - traefik.http.routers.landing.tls.certresolver=mytlschallenge
      - traefik.http.services.landing.loadbalancer.server.port=80
    networks:
      - shared_proxy_net
    restart: unless-stopped

networks:
  shared_proxy_net:
    external: true
